### ISSUE TITLE
Installing through npm does not include index.js

### ISSUE THREAD

**Issue by SijanC147** [bradbaris/imagemin-guetzli#3]
Just tried installing this through npm (and yarn) and was getting a 'module not found' error on webpack due to the fact that no index.js file was being pulled. 

Module works perfectly if i add it from this repo directly.

**Comment by clocked0ne** [comment]
I've literally just experienced the same problem, high five ✋

**Comment by clocked0ne** [comment]
FYI
```bash
npm install --save-dev imagemin-guetzli@0.1.1
```
works fine

**Comment by SijanC147** [comment]
✋️cheers will update accordingly.

**Comment by bradbaris** [comment]
Woops, seems to be a form of [this](https://github.com/npm/npm/issues/5082). The machine I was on had an older version of npm `3.8.6`. Updated to `4.4.1` and just sent it through again. Thanks!
