### ISSUE TITLE
Include threshold image size option

### ISSUE THREAD

**Issue by SijanC147** [bradbaris/imagemin-guetzli#4]
Would be great if this plugin accepted an image file size threshold option since guetzli is better suited for larger, higher quality, images.

**Comment by bradbaris** [comment]
That might be straying from the module objective. Maybe someone just wants to optimize images with the guetzli paradigm, regardless of file size or savings. Others may integrate it differently, so I'd rather keep it simple: let users decide what they want to guetzli.

If you are integrating with gulp, you could try filtering globs by file size before piping it in.

**Comment by SijanC147** [comment]
Understood, actually using webpack atm, but i get what you mean, i'll look into applying this filter at a higher level. Thank you
