### ISSUE TITLE
grunt support?

### ISSUE THREAD

**Issue by genericandy** [bradbaris/imagemin-guetzli#7]
Im trying to use imagemin-guetzli with a gruntfile here & getting errors I can't account for:

Here is the relevant part of the code from the file:

`
module.exports = function(grunt) {

	var pngquant = require('imagemin-pngquant'),
		jpegRecompress = require('imagemin-jpeg-recompress'),
		imageminGuetzli = require('imagemin-guetzli');
		imagemin: {
			rel: {
				options: {
    				use: [ imageminGuetzli() ]
				},
				files: [{
					expand: true,
					cwd: appConfig.app + '/',
					src: ['**/*.{png,jpg,gif}', '!bower_components/**'],
					dest: appConfig.rel + '/'
				}]
			}
		}`

The error Im getting is below. Any suggestions would be appreciated.

> Running "imagemin:rel" (imagemin) task
(node:15434) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Expected a buffer
(node:15434) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15434) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Expected a buffer

**Comment by bradbaris** [comment]
Your issue is gruntjs/grunt-contrib-imagemin#372. Unfortunately, as you'll find, imagemin plugins hardly support Grunt anymore. A typical workaround is to install an earlier version, but `imagemin-guetzli` was created long after the imagemin plugin move from streams to Promises.

**Comment by sindresorhus** [comment]
Nothing we can do about. Complain on the `grunt-contrib-imagemin` issue tracker about them updating the `imagemin` dependency.

**Comment by genericandy** [comment]
Thanks, I've been looking to move away from Grunt soon anyway. This is just one more reason on the list.
